### ISSUE TITLE
PHP Code Error

### ISSUE THREAD

**Issue by ghost** [jasonpau/jp-facebook-album#7]
Warning: require_once(/home/***MY USER****/public_html/staging/wp-content/plugins/jp-facebook-album-develop/vendor/autoload.php): failed to open stream: No such file or directory in /home/***MY USER****/public_html/staging/wp-content/plugins/jp-facebook-album-develop/jp-facebook-album.php on line 16

Fatal error: require_once(): Failed opening required '/home/***MY USER****/public_html/staging/wp-content/plugins/jp-facebook-album-develop/vendor/autoload.php' (include_path='.:/opt/cpanel/ea-php72/root/usr/share/pear') in /home/***MY USER****/public_html/staging/wp-content/plugins/jp-facebook-album-develop/jp-facebook-album.php on line 16

**Comment by jasonpau** [comment]
@thesheryar Sorry for the late reply, I'm sure you've already resolved it on your own or moved on, but in case anybody else stumbles across this; did you run `composer install` from within the plugin folder?

**Comment by jasonpau** [comment]
Closing this as it's coming up on two years with no response from the OP.
